# routes/counselor_routes.py
from fastapi import APIRouter, Depends, HTTPException
from services.analytics import compute_counselor_analytics
from services.pdf_generator import generate_pdf_report
from models.schemas import AnalyticsRequest, PDFRequest
from dependencies.auth import get_current_user  # placeholder for your auth
from typing import Optional
from datetime import datetime
import base64

router = APIRouter(prefix="/counselor", tags=["counselor"])

@router.post("/analytics")
async def counselor_analytics(req: AnalyticsRequest, current_user = Depends(get_current_user)):
    # ensure user is counselor or admin
    if current_user.role not in ("counselor", "admin"):
        raise HTTPException(status_code=403, detail="Not authorized")
    counselor_id = req.counselor_id or current_user.id
    result = await compute_counselor_analytics(counselor_id, req.start_date, req.end_date)
    # convert binary charts to base64 for JSON transport
    charts_b64 = {}
    for k, v in result.get("charts", {}).items():
        charts_b64[k] = base64.b64encode(v).decode()
    result["charts_b64"] = charts_b64
    return result

@router.post("/analytics/pdf")
async def counselor_analytics_pdf(req: PDFRequest, current_user = Depends(get_current_user)):
    if current_user.role not in ("counselor", "admin"):
        raise HTTPException(status_code=403, detail="Not authorized")
    counselor_id = req.counselor_id or current_user.id
    # compute
    analytics = await compute_counselor_analytics(counselor_id, req.start_date, req.end_date)
    pdf_bytes = await generate_pdf_report(
        title=f"Counselor Analytics - {counselor_id}",
        charts=analytics.get("charts", {}),
        insights=analytics.get("insights", []),
        details_text="Generated by PsyHub analytics"
    )
    return {"filename": f"counselor_{counselor_id}_analytics.pdf", "pdf_base64": base64.b64encode(pdf_bytes).decode()}
